spring:
  profiles:
    active:
    - local
---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  server:
    port: 5432