spring:
  profiles:
    active:
    - dev
---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/sample_db
    driver-class-name: org.postgresql.Driver
    username:
    password:
  server:
    port: 5433