spring:
  application:
    name: cusotmer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

customer:
  service:
    source:
      code: nirmal