spring:
  application:
    name: cusotmer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  server:
    port: 5432

server:
  port: 8080

customer:
  service:
    source:
      code: nirmal